#!/usr/bin/env perl
# Copyright 2010-2011 Kevin Spencer <kevin@kevinspencer.org>
#
# Permission to use, copy, modify, distribute, and sell this software and its
# documentation for any purpose is hereby granted without fee, provided that
# the above copyright notice appear in all copies and that both that
# copyright notice and this permission notice appear in supporting
# documentation. No representations are made about the suitability of this
# software for any purpose. It is provided "as is" without express or
# implied warranty.
#
################################################################################

use JSON::Any;
use LWP::UserAgent;
use strict;
use warnings;

our $VERSION = '0.02';

my $shorturl = shift;

my $ua = LWP::UserAgent->new();
$ua->agent("expandurl/0.02");

my $api_url = "http://api.longurl.org/v2/expand?url=$shorturl&format=json";

my $response = $ua->get($api_url);
if ($response->is_success()) {
    my $obj = JSON::Any->jsonToObj($response->decoded_content());
    print $obj->{'long-url'}, "\n";
} else {
    print $response->status_line(), "\n";
}
